### ISSUE TITLE
Can't build with caddy v1.0.4

### ISSUE THREAD

**Issue by brendony** [BTBurke/caddy-extauth#4]
Hi, due to the move from `mholt/caddy` to `caddyserver/caddy` this plugin doesn't build at the moment.

I've forked your repo to `brendony/caddy-extauth` and changed it 'til it built.   My changes don't translate well to a pull request because it refers to `brendony` in some parts of the code.

Apologies (I'm not a gopher), I also had to make a release v0.6.1 to be able to build things. It's all new to me!

Thanks, 
Brendon

ps. Are you intending on making this plugin available in the main caddy site?

**Comment by BTBurke** [comment]
I've basically abandoned this because there is a new V2 version of Caddy that will be released very soon.  All of these legacy plugins will be deprecated and they will likely have to be substantially rewritten for the new version.  I'm not sure whether I will do that.

**Comment by brendony** [comment]
Ah, fair enough!

Thanks for letting me know. I appreciate your jwt plugin too.

**Comment by BTBurke** [comment]
Thanks.  Knowing that people use this stuff is helpful when deciding whether its worth the effort to port them to the new caddy plugin architecture.
